# Generated by Django 4.1.7 on 2023-04-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0007_alter_dokter_tarif_alter_hewan_umur_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentDokter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_id", models.CharField(max_length=10, unique=True)),
                ("appointment_date", models.DateTimeField()),
                (
                    "dokter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.dokter"
                    ),
                ),
                (
                    "hewan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.hewan"
                    ),
                ),
                (
                    "pemilik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
            ],
        ),
    ]
