# Generated by Django 4.1.7 on 2023-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentdokter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmentdokter",
            old_name="appointment_date",
            new_name="appointment_time",
        ),
        migrations.AddField(
            model_name="appointmentdokter",
            name="keluhan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentdokter",
            name="status",
            field=models.CharField(
                choices=[
                    ("Menunggu Konfirmasi", "Menunggu Konfirmasi"),
                    ("Disetujui", "Disetujui"),
                    ("Ditolak", "Ditolak"),
                ],
                default="Menunggu Konfirmasi",
                max_length=40,
            ),
        ),
    ]
