# Generated by Django 4.1.7 on 2023-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentdokter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentdokter",
            name="alasan",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="appointmentdokter",
            name="status",
            field=models.CharField(
                choices=[
                    ("Menunggu Konfirmasi", "Menunggu Konfirmasi"),
                    ("Disetujui", "Disetujui"),
                    ("Ditolak", "Ditolak"),
                    ("Dibatalkan", "Dibatalkan"),
                    ("Selesai", "Selesai"),
                ],
                default="Menunggu Konfirmasi",
                max_length=40,
            ),
        ),
    ]
