# Generated by Django 4.1.7 on 2023-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_event",
            name="id",
            field=models.CharField(
                default="hNr2W6",
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
