# Generated by Django 4.1.7 on 2023-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='specific_location',
            field=models.CharField(max_length=100),
        ),
    ]
