# Generated by Django 4.1.7 on 2023-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_specific_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
