# Generated by Django 4.1.7 on 2023-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customer_events_attended'),
        ('events', '0004_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attended', to='user.Customer'),
        ),
    ]

