# Generated by Django 4.1.7 on 2023-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_jenis_alter_register_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register_event',
            name='id',
            field=models.CharField(default='csesS4', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
