# Generated by Django 4.1.7 on 2023-04-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customer_events_attended'),
        ('events', '0005_alter_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='events_attended', to='user.customer'),
        ),
    ]
