# Generated by Django 4.1.7 on 2023-04-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_mendaftar_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mendaftar_Event',
        ),
    ]
