# Generated by Django 4.1.7 on 2023-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_register_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='register_event',
            name='id',
            field=models.CharField(default='4HfKCK', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
