# Generated by Django 4.1.7 on 2023-04-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_register_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_event',
            name='id',
            field=models.CharField(default='QypDiX', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
