# Generated by Django 4.1.7 on 2023-04-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_produk'),
        ('adopsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Adopsi',
            fields=[
                ('id', models.CharField(default='gw33Fn', editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopsi.adopsi')),
            ],
        ),
    ]
