# Generated by Django 4.1.7 on 2023-04-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0002_register_adopsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_adopsi',
            name='id',
            field=models.CharField(default='ProQf7', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
