# Generated by Django 4.1.7 on 2023-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0003_alter_register_adopsi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopsi',
            name='status',
            field=models.CharField(choices=[('Belum diadopsi', 'Belum diadopsi'), ('Diadopsi', 'Diadopsi')], default='Belum diadopsi', max_length=50),
        ),
        migrations.DeleteModel(
            name='Register_Adopsi',
        ),
    ]
