# Generated by Django 4.1.7 on 2023-05-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopsi', '0005_alter_register_adopsi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopsi',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register_adopsi',
            name='date_adopted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='register_adopsi',
            name='id',
            field=models.CharField(default='KpYwJm', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
