# Generated by Django 4.1.7 on 2023-03-14 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pengguna",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("role", models.IntegerField()),
                ("email", models.EmailField(blank=True, max_length=70, unique=True)),
                ("notelepon", models.CharField(max_length=12)),
                ("password", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
            ],
        ),
    ]
