# Generated by Django 4.1.7 on 2023-03-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginlogout", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Pengguna",),
    ]
