# Generated by Django 4.1.7 on 2023-05-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_groomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentGrooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=10, unique=True)),
                ('appointment_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu Konfirmasi', max_length=40)),
                ('total_biaya', models.IntegerField()),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.hewan')),
                ('layanan_tambahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan_tambahan_appointmentgrooming', to='user.produk')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_appointmentgrooming', to='user.produk')),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
