# Generated by Django 4.1.7 on 2023-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groomer'),
        ('appointmentgrooming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentgrooming',
            name='layanan_tambahan',
        ),
        migrations.AddField(
            model_name='appointmentgrooming',
            name='layanan_tambahan',
            field=models.ManyToManyField(related_name='layanan_tambahan_appointmentgrooming', to='user.produk'),
        ),
    ]
