# Generated by Django 4.1.7 on 2023-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groomer'),
        ('appointmentgrooming', '0002_remove_appointmentgrooming_layanan_tambahan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentgrooming',
            name='layanan_tambahan',
            field=models.ManyToManyField(blank=True, related_name='layanan_tambahan_appointmentgrooming', to='user.produk'),
        ),
    ]
