# Generated by Django 4.1.7 on 2023-05-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentgrooming', '0003_alter_appointmentgrooming_layanan_tambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentgrooming',
            name='alasan',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appointmentgrooming',
            name='harga_paket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointmentgrooming',
            name='layanan_tambahan_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentgrooming',
            name='nama_paket',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentgrooming',
            name='status',
            field=models.CharField(choices=[('Menunggu Konfirmasi', 'Menunggu Konfirmasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Dibatalkan', 'Dibatalkan'), ('Selesai', 'Selesai')], default='Menunggu Konfirmasi', max_length=40),
        ),
    ]
