# Generated by Django 4.1.7 on 2023-03-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
