# Generated by Django 4.1.7 on 2023-03-16 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('no_telepon', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
