# Generated by Django 4.1.7 on 2023-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='tarif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Karyawan', 'Karyawan'), ('Dokter', 'Dokter'), ('Groomer', 'Groomer')], max_length=40),
        ),
    ]
