# Generated by Django 4.1.7 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_attendees'),
        ('user', '0007_alter_dokter_tarif_alter_hewan_umur_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='events_attended',
            field=models.ManyToManyField(related_name='events_attended', to='events.event'),
        ),
    ]
