# Generated by Django 4.1.7 on 2023-04-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customer_events_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='events_attended',
        ),
    ]
