# Generated by Django 4.1.7 on 2023-04-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipValidation',
            fields=[
                ('vip_validation_id', models.AutoField(primary_key=True, serialize=False)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('bukti_pembayaran', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.customer')),
            ],
        ),
    ]
