<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-26 15:56
=======
# Generated by Django 4.1.7 on 2023-04-12 15:04
>>>>>>> 2ca4c9cc887c49ad87fe40189268c775b1192204

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('profileuser', '0001_initial'),
=======
        ("profileuser", "0001_initial"),
>>>>>>> 2ca4c9cc887c49ad87fe40189268c775b1192204
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='VipValidation',
            fields=[
                ('vip_validation_id', models.AutoField(primary_key=True, serialize=False)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('bukti_pembayaran', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileuser.customer')),
=======
            name="VipValidation",
            fields=[
                (
                    "vip_validation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("metode_pembayaran", models.CharField(max_length=50)),
                (
                    "bukti_pembayaran",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profileuser.customer",
                    ),
                ),
>>>>>>> 2ca4c9cc887c49ad87fe40189268c775b1192204
            ],
        ),
    ]
