# Generated by Django 4.1.7 on 2023-03-20 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
       
       
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('hewan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=50)),
                ('umur', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                
            ],
        ),
    ]
