# Generated by Django 4.1.7 on 2023-03-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='hewan',
            name='pemilik',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Dokter',
        ),
        migrations.DeleteModel(
            name='Hewan',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
