# Generated by Django 4.1.7 on 2023-05-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sirad", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Hewan",),
    ]
